# Generated by Django 4.1.6 on 2024-02-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=16, unique=True)),
                ('peso', models.FloatField()),
                ('nascimento', models.DateTimeField()),
                ('raca', models.CharField(max_length=20, null=True)),
                ('cor', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tag.tag')),
            ],
        ),
    ]
